### PR TITLE
Update GitHub Actions and commit package-lock.json

### PR DESCRIPTION
**Pull request by ouuan**
https://docs.npmjs.com/configuring-npm/package-lock-json.html:

> This file is intended to be committed into source repositories, and
serves various purposes:
>
> - Describe a single representation of a dependency tree such that
>   teammates, deployments, and continuous integration are guaranteed
>   to install exactly the same dependencies.
>
> - Provide a facility for users to “time-travel” to previous states of
>   node_modules without having to commit the directory itself.
>
> - To facilitate greater visibility of tree changes through readable
>   source control diffs.
>
> - And optimize the installation process by allowing npm to skip
>   repeated metadata resolutions for previously-installed packages.

And package.json is somehow required by caching dependencies.

### CODE REVIEW

**Comment by ouuan** [comment]
这个 `GH_TOKEN` 是 personal access token 吗？可以用 `secrets.GITHUB_TOKEN`，不需要手动设置。这样的话 fork 也不用手动设置。

**Comment by simon300000** [comment]
嗯我这样试试

**Comment by ouuan** [comment]
https://github.com/actions/checkout/commit/422dc4567157f4d62b665a8a288310365b1d194b

checkout v2 支持 submodules 两个多月了我才发现..之前是只有 v1 可以，所以我自己都是用 v2 然后手动 `git submodule update --init --recursive`。

**Comment by ouuan** [comment]
这个 Windows 的 Cache dependencies 貌似是负优化..

**Comment by simon300000** [comment]
Windows一直是最慢的那个
不过没想到那么大
image

大概是windows那个位置有什么特殊的东西？别的dou只有40mb左右

**Pull request merged**
